name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for PostForge? We'd love to hear it.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why is this useful? What problem does it solve?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you found any workarounds or alternative approaches?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of PostForge does this relate to?
      options:
        - PostScript operators / language
        - PNG output
        - PDF output
        - SVG output
        - Qt display
        - CLI / usability
        - Performance
        - Documentation
        - Other
    validations:
      required: false
